# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='in_archive',
            field=models.BooleanField(default=False),
        ),
    ]
